-- Catálogo de asignaturas (curriculum subjects) para PACI y otros documentos.
-- Tabla en inglés: curriculum_subjects. UI muestra name_es; name es identificador en inglés.

CREATE TABLE IF NOT EXISTS curriculum_subjects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT 'Subject name in English',
  name_es VARCHAR(255) NOT NULL COMMENT 'Nombre en español (etiqueta UI)',
  category VARCHAR(64) NULL COMMENT 'arts, language, mathematics, sciences, social_studies, transition_level, technology, physical_education, english, other',
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  added_date DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_date DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_curriculum_subjects_name_es (name_es),
  KEY idx_curriculum_subjects_category (category),
  KEY idx_curriculum_subjects_active (is_active, deleted_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO curriculum_subjects (name, name_es, category, sort_order) VALUES
('Visual Arts', 'Artes visuales', 'arts', 1),
('Natural Sciences', 'Ciencias Naturales', 'sciences', 2),
('Natural Sciences - Biology', 'Ciencias Naturales - Biología', 'sciences', 3),
('Natural Sciences - Physics', 'Ciencias Naturales - Física', 'sciences', 4),
('Natural Sciences - Chemistry', 'Ciencias Naturales - Química', 'sciences', 5),
('Sciences for Citizenship - Environment and Sustainability', 'Ciencias para la ciudadanía - Ambiente y sostenibilidad', 'sciences', 6),
('Sciences for Citizenship - Well-being and Health', 'Ciencias para la ciudadanía - Bienestar y salud', 'sciences', 7),
('Sciences for Citizenship - Safety, Prevention and Self-care', 'Ciencias para la ciudadanía - Seguridad, prevención y autocuidado', 'sciences', 8),
('Sciences for Citizenship - Technology and Society', 'Ciencias para la ciudadanía - Tecnología y sociedad', 'sciences', 9),
('Civic Education', 'Educación Ciudadana', 'social_studies', 10),
('Physical Education and Health', 'Educación física y salud', 'physical_education', 11),
('History, Geography and Social Sciences', 'Historia, Geografía y Ciencias Sociales', 'social_studies', 12),
('English', 'Inglés', 'english', 13),
('English (Proposal)', 'Inglés (Propuesta)', 'english', 14),
('Language and Culture of Indigenous Peoples', 'Lengua y Cultura de los Pueblos Originarios', 'language', 15),
('Language and Literature - Specialized Reading and Writing', 'Lengua y literatura - Lectura y escritura especializada', 'language', 16),
('Language and Literature - Participation and Argumentation in Democracy', 'Lengua y literatura - Participación y argumentación en democracia', 'language', 17),
('Language and Literature - General Training Plan', 'Lengua y literatura - Plan de Formación General', 'language', 18),
('Language and Literature - Literature Workshop', 'Lengua y literatura - Taller de literatura', 'language', 19),
('Language and Communication', 'Lenguaje y comunicación', 'language', 20),
('Mathematics', 'Matemática', 'mathematics', 21),
('Mathematics - Geometry', 'Matemática - Geometría', 'mathematics', 22),
('Mathematics - Limits, Derivatives and Integrals', 'Matemática - Límites, derivadas e integrales', 'mathematics', 23),
('Mathematics - Computational Thinking and Programming', 'Matemática - Pensamiento computacional y programación', 'mathematics', 24),
('Mathematics - General Training Plan', 'Matemática - Plan de Formación General', 'mathematics', 25),
('Mathematics - Probability and Descriptive and Inferential Statistics', 'Matemática - Probabilidades y estadística descriptiva e inferencial', 'mathematics', 26),
('Music', 'Música', 'arts', 27),
('Transition Level - Understanding of the Socio-cultural Environment', 'NT - Comprensión del entorno sociocultural', 'transition_level', 28),
('Transition Level - Coexistence and Citizenship', 'NT - Convivencia y ciudadanía', 'transition_level', 29),
('Transition Level - Corporality and Movement', 'NT - Corporalidad y movimiento', 'transition_level', 30),
('Transition Level - Exploration of the Natural Environment', 'NT - Exploración del entorno natural', 'transition_level', 31),
('Transition Level - Identity and Autonomy', 'NT - Identidad y autonomía', 'transition_level', 32),
('Transition Level - Verbal Language', 'NT - Lenguaje verbal', 'transition_level', 33),
('Transition Level - Artistic Languages', 'NT - Lenguajes artísticos', 'transition_level', 34),
('Transition Level - Mathematical Thinking', 'NT - Pensamiento matemático', 'transition_level', 35),
('Technology', 'Tecnología', 'technology', 36),
('Arts - General Training Plan', 'Artes - Plan de Formación General', 'arts', 37);
